name: Publish website to GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: sphinxdoc/sphinx:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Build Sphinx website
        run: make dirhtml
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./_build/dirhtml

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
